name: gloclone
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  lucide_icons: ^0.257.0
  fluttertoast: ^9.1.0
  nepali_utils: ^3.0.8
  nepali_date_picker: ^7.0.1

  # Shared preferences & Firebase components
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/sunflower.png
    - assets/images/rose.png
    - assets/images/blue_flower.png
    - assets/images/cactus.png
    - assets/images/purple_flower.png
    - assets/images/whiteheads.png
    - assets/images/blackheads.png
    - assets/images/papules.png
    - assets/images/pustules.png
    - assets/images/nodules.png
    - assets/images/cystic.png
    - assets/images/acnetracker.png
    - assets/images/flower.png
    - assets/images/journal.png
    - assets/images/logo.png
    - assets/images/medication.png
    - assets/images/skinderma.png
    - assets/images/stressandsleep.png
    - assets/images/watertracker.png