import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:provider/provider.dart';

import 'view/JournalEntryScreen.dart';
import 'view/ActivitySelectionScreen.dart';
import 'viewmodel/journal_entry_viewmodel.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => JournalEntryViewModel(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'GLO Clone',
      theme: ThemeData(
        primarySwatch: Colors.pink,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const JournalEntryScreen(),
        '/activity': (context) => ActivitySelectionScreen(
          initialSelections: {
            "Physical Activity": "Add",
            "Self Care": "Add",
            "Lifestyle": "Add",
            "Mood": "Add",
          },
        ),
      },
    );
  }
}
