import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

// Firebase options (generated by FlutterFire CLI)
import 'firebase_options.dart';

// ViewModel
import 'package:gloclone/viewmodel/wellness_viewmodel.dart';

// Screens
import 'package:gloclone/view/wellness_dashboard_screen.dart';
import 'package:gloclone/view/mood_log_screen.dart';
import 'package:gloclone/view/mood_summary_screen.dart';
import 'package:gloclone/view/mood_calendar_screen.dart';
import 'package:gloclone/view/mood_garden_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) {
            final vm = WellnessViewModel();
            // Use FirebaseAuth user ID if available
            final userId = FirebaseAuth.instance.currentUser?.uid ?? "guest";
            vm.initUserSync(userId);
            return vm;
          },
        ),
        // Add other ViewModels here if needed
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Wellness App',
      theme: ThemeData(useMaterial3: true),

      // Launch directly into your MVVM dashboard
      home: const WellnessDashboardScreen(),

      // Define routes for navigation
      routes: {
        '/mood_log': (_) => const MoodLogScreen(),
        '/mood_summary': (_) => const MoodSummaryScreen(),
        '/mood_calendar': (_) => const MoodCalendarScreen(),
        '/mood_garden': (_) => const MoodGardenScreen(),
      },
    );
  }
}
