import 'package:flutter/material.dart';
import 'package:Glo/models/notification_model.dart';

class NotificationRepository {
  Future<List<NotificationModel>> fetchNotificationsFromBackend() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      NotificationModel(
        id: 1,
        section: 'Today',
        title: 'Ovulation in 2 days',
        tag: 'Ovulation',
        description: 'Your fertile window is starting soon. Take care! 🌸',
        time: '9:00 AM',
        icon: '🌸',
        iconBg: const Color(0xFFFFE3E6),
        isUnread: true,
      ),
      NotificationModel(
        id: 2,
        section: 'Today',
        title: 'Stay Hydrated!',
        tag: 'Water Tracker',
        description: 'Time to drink a glass of water. Keep your body happy! 💧',
        time: '9:30 AM',
        icon: '💧',
        iconBg: const Color(0xFFE3F2FD),
        isUnread: true,
      ),
      NotificationModel(
        id: 3,
        section: 'Today',
        title: 'Time to take Iron Supplement',
        tag: 'Medication',
        description: 'Consistency is the key to better health. 💊',
        time: '10:00 AM',
        icon: '💊',
        iconBg: const Color(0xFFFFF2CC),
        isUnread: true,
      ),
      NotificationModel(
        id: 4,
        section: 'Today',
        title: 'Don\'t forget to log your mood',
        tag: 'Mood Tracker',
        description: 'How are you feeling today?\nYour Mood Garden misses you! 🏡',
        time: '12:00 PM',
        icon: '😊',
        iconBg: const Color(0xFFFFEAA7),
        isUnread: true,
      ),
      NotificationModel(
        id: 5,
        section: 'Yesterday',
        title: 'Derma Visit Tomorrow',
        tag: 'Derma Visit',
        description: 'You have a dermatology appointment tomorrow at 10:00 AM.',
        time: '8:00 PM',
        icon: '👩‍⚕️',
        iconBg: const Color(0xFFE3F2FD),
        isUnread: true,
      ),
      NotificationModel(
        id: 6,
        section: 'Yesterday',
        title: 'Water goal achieved! 🎉',
        tag: 'Water Tracker',
        description: 'Awesome job! You reached your 2.5L target yesterday.',
        time: '8:30 PM',
        icon: '🥤',
        iconBg: const Color(0xFFE0F7FA),
        isUnread: false,
      ),
      NotificationModel(
        id: 7,
        section: 'Yesterday',
        title: 'Period expected in 3 days',
        tag: 'Period',
        description: 'Your period is expected on April 06, 2026.',
        time: '7:00 PM',
        icon: '🩸',
        iconBg: const Color(0xFFFFEBEE),
        isUnread: false,
      ),
      NotificationModel(
        id: 8,
        section: 'Yesterday',
        title: 'Period log reminder',
        tag: 'Period Log',
        description: 'You haven\'t logged your period today. Update your cycle.',
        time: '6:00 PM',
        icon: '📅',
        iconBg: const Color(0xFFF3E5F5),
        isUnread: true,
      ),
      NotificationModel(
        id: 9,
        section: 'Yesterday',
        title: 'Journal reminder',
        tag: 'Journal',
        description: 'Write down your thoughts and feelings of today. ✨',
        time: '9:00 PM',
        icon: '📖',
        iconBg: const Color(0xFFE8F5E9),
        isUnread: true,
      ),
    ];
  }
}